steps:
- name: crosstalkio/webrtc-android-builder
  dir: /workspace
  entrypoint: fetch
  args: ['--nohooks', 'webrtc_android']
- name: crosstalkio/webrtc-android-builder
  dir: /workspace/src
  entrypoint: git
  args: ['fetch', 'origin']
- name: crosstalkio/webrtc-android-builder
  dir: /workspace/src
  entrypoint: git
  args: ['checkout', 'd25c2ac74afc25f65d111771dbfabd6db25d2498']
- name: crosstalkio/webrtc-android-builder
  entrypoint: rm
  args: ['-rf', '/workspace/.cipd']
- name: crosstalkio/webrtc-android-builder
  dir: /workspace/src
  entrypoint: gclient
  args: ['sync', '-D']
- name: crosstalkio/webrtc-android-builder
  dir: /workspace/src
  entrypoint: git
  args: ['apply', '/workspace/patches/tethering.patch']
- name: crosstalkio/webrtc-android-builder
  dir: /workspace/src
  entrypoint: git
  args: ['apply', '/workspace/patches/mediacodec_whitelist_and_platform_encoder.patch']
- name: crosstalkio/webrtc-android-builder
  dir: /workspace/src
  entrypoint: git
  args: ['apply', '/workspace/patches/apprtc_hwencode_whitelist.patch']
- name: crosstalkio/webrtc-android-builder
  dir: /workspace/src
  entrypoint: git
  args: ['apply', '/workspace/patches/inter_arrival.patch']
- name: crosstalkio/webrtc-android-builder
  dir: /workspace/src
  entrypoint: git
  args: ['apply', '/workspace/patches/htc_desire_816_vp8_encoder_init_error_and_reset_on_encoder_error.patch']
- name: crosstalkio/webrtc-android-builder
  dir: /workspace/src
  entrypoint: git
  args: ['apply', '/workspace/patches/enable_implicit_rollback.patch']
- name: crosstalkio/webrtc-android-builder
  dir: /workspace/src
  entrypoint: git
  args: ['apply', '/workspace/patches/bintray_release_aar.patch']
- name: crosstalkio/webrtc-android-builder
  env:
    - 'BINTRAY_USER=${_BINTRAY_USER}'
    - 'BINTRAY_API_KEY=${_BINTRAY_API_KEY}'
  dir: /workspace/src
  entrypoint: python
  args: ['tools_webrtc/android/release_aar.py', '--skip-tests']
timeout: 7200s
options:
  machineType: 'N1_HIGHCPU_32'
